### PR TITLE
Add past types for Pokémon

### PR DESCRIPTION
**Pull request by JoostFranssen**
This adds the field past_types to Pokemon: https://pokeapi.co/docs/v2#pokemontypepast

### CODE REVIEW

**Comment by SirSkaro** [comment]
This is fantastic! Could set the version to 1.0.4 instead of 1.0.5 please? I'll happy merge and create another release.

**Comment by JoostFranssen** [comment]
Glad to help! I've corrected the version number and will take note of it if I need to make any more pull requests. Thanks for responding to these so quickly (and for his project as a whole)!

**Comment by SirSkaro** [comment]
[Version 1.0.4](https://github.com/SirSkaro/pokeapi-reactor/packages/1173543) is published!
Thank you! I try to follow [semantic versioning](https://semver.org/), though I may not be. I think technically these changes constitute as a minor change instead of a patch change (because they are non-backward compatible changes on the getters/setters). So I think going to 1.0.4 instead of 1.1.0 violates semantic versioning's specifications. I just have a hard time going from 1.0.X to 1.1.0 because of changing the signature of a few getters and setters, lol. So perhaps I'm being a bit picky/inconsistent. 

Glad you're finding the project useful. Really appreciate you contributing and fixing my bugs - happy coding!

**Comment by JoostFranssen** [comment]
Great, thanks!
Yea, I understand that. Seems too minor for 1.1.0, even if technically it should be. (Then again, before you got a json-parsing exception on that field, so everything that worked in the previous version technically still works haha.)

**Pull request merged**
